# Generated by Django 2.0.13 on 2019-06-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='dive_site',
        ),
        migrations.AddField(
            model_name='post',
            name='city_state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty_level',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
