# Generated by Django 2.0.13 on 2019-06-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190622_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city_country',
            new_name='city_state',
        ),
    ]
